### ISSUE TITLE
这个是否可以放到GAE上面？

### ISSUE THREAD

**Issue by grvip** [hyqhyq3/avsocks#1]
这个是用Go语言开发的吗？请问能不能修改一下使之能够放到GAE上面呢？那样用起来就方便多了

**Comment by hyqhyq3** [comment]
是用Go开发的,不过GAE不支持直接使用net库,只支持用urlfetch. urlfetch只支持http协议,并且GoAgent已经实现了这样的功能,所以我觉得没有必要把这个程序改得可以在GAE上使用.
本程序与GoAgent相比,易用性的确没那么高,不过优点在于服务器端使用的是原生的Socket去抓去内容,而不是httpclient,这样可以支持绝大多数基于TCP协议的程序(FTP在使用被动模式时,需要客户端主动监听连接,这个由于Socks5协议本身讲得不明不白,所以没有支持).

如果你只用于普通的上网看网页,并且不觉得GoAgent速度慢的话,我建议你使用GoAgent就行.
希望你能理解我的懒惰…XD

在 2012-12-5，下午9:40，grvip notifications@github.com 写道：
